python/requirements.txt
python/server.py

Added required package to requirements.txt and fixed a view conflict in server.py.  The view conflict came from naming a function 'transactions' twice.
Also added in a couple comments on the namespaces (PLAID_SECRET, PLAID_CLIENT_ID , PLAID_PUBLIC_KEY, PLAID_ENV)

Modified requirements.txt and server.py

---

python/server.py

So Python developers can export settings and run the demo without changing the code.

Read configuration from environment variables

---

node/index.js

Errors would appear in the console as [object Object] otherwise.

Stringify error objects when logging

---

node/package.json
python/requirements.txt

Fixes #44 
Also updates Python Quickstart app dependencies

update quickstart dependencies

---

python/requirements.txt
python/server.py

Hi there,
I just made some minor updates to the requirements.txt and server.py for Python 3 compatibility.
I tested the changes against Python 3.7.1 and 2.7.15rc1.
These updates address issue #37.
-Zach

Updated requirements.txt and server.py for Python 3 compatibility. (Issue #37)

---

node/index.js

Hi there!
I kept getting `SyntaxError: Unexpected token )` errors so I had to remove trailing commas in 4 different parts of `index.js`
Not sure if is something related to my own environment.
Thanks,
Luigi

Trailing commas issue for Node.js

---

ruby/app.rb
ruby/views/index.erb

This takes off much of the recnet investments code and existing Ruby code. Tested on Sandbox and Development with my Client keys

adds investment transactions and holdings to the quickstart

---

ruby/app.rb
ruby/static/style.css
ruby/views/index.erb

Implements UK Payment Initiation support in Ruby.
Tested locally that both payment-initiation and the default flow work successfully.

Implements UK Payment Initiation support in Ruby

---

node/index.js
node/public/style.css
node/views/index.ejs

Implements UK Payment Initiation support in Node.
Tested locally that both payment-initiation and the default flow work successfully.

Implements UK Payment Initiation support in Node

---

java/README.md
java/config.yml
java/pom.xml
java/src/main/java/com/plaid/quickstart/QuickstartApplication.java
java/src/main/java/com/plaid/quickstart/QuickstartConfiguration.java
java/src/main/java/com/plaid/quickstart/resources/IndexResource.java
java/src/main/java/com/plaid/quickstart/resources/PaymentInitiationResource.java
java/src/main/resources/static/style.css
java/src/main/resources/templates/index.ftl
node/index.js

Implements UK Payment Initiation support in Java.
Tested locally that both payment-initiation and the default flow work successfully.

Implements UK Payment Initiation support in Java

---

python/server.py
python/static/style.css
python/templates/index.ejs

Implements UK Payment Initiation support in Python.
Tested locally that both payment-initiation and the default flow work successfully.

Implements UK Payment Initiation support in Python

---

ruby/README.md
ruby/app.rb
ruby/views/index.erb
ruby/views/oauthresponse.erb

Copies https://github.com/plaid/quickstart/pull/91 for Ruby
I tested that this PR works locally for the OAuth flows and does not break the existing classic Plaid Quickstart flow.

Implements OAuth Ruby support

---

python/README.md
python/server.py
python/templates/index.ejs
python/templates/oauth-response.ejs

Copies #91 for Python
I tested that this PR works locally for the OAuth flows and does not break the existing classic Plaid Quickstart flow.

Implements OAuth Python support

---

node/public/style.css
node/views/index.ejs

The latest change to the API changed how the Identity endpoint worked. 
[Version changelog 2019-05-29](plaid.com/docs/api-upgrades/#date-2019-05-29)
I updated the Node version of the quickstart project to reflect these changes.

updated the identity endpoint to match the latest api revision

---

go/README.md
go/server.go
java/README.md
node/README.md
node/index.js
python/README.md
python/server.py
ruby/README.md
ruby/views/index.erb

This PR updates the Quickstart to include Netherlands as a country code by default.

Update Quickstart to include Netherlands

---

go/templates/index.tmpl
python/templates/index.ejs
ruby/views/index.erb

Turns out Identity was broken in 3 of the quickstarts.  This fixes it.

Fix broken identity button

---

README.md
docker-compose.yml
go/Dockerfile
java/Dockerfile
node/Dockerfile
node/index.js
python/Dockerfile
python/server.py
ruby/Dockerfile

Update the root readme to no longer reference the public_key.
Update the docker-compose and docker files to work with new shared FE.

update docker-compose and root readme

---

html/index.html

Display errors if they occur for /link/token/create

display error message on link_token req failure

---

ruby/README.md

Tested locally to update the quickstart oauth command as needed.

Updates ruby oauth readme

---

README.md

Adding comment about Windows and using symlinks to clone the project so that it works.

Update README.md to reflect Windows usage.

---

README.md

Update README.md to clarify OAuth env limitations

---

python/static/style.css

This file has border-radius specified twice.  Fixed it.

Fix duplicate border-radius

---

frontend/src/App.tsx
frontend/src/Components/Link/index.tsx
frontend/src/Components/Table/Identity.tsx
frontend/src/Components/Table/index.tsx
frontend/src/Context/index.tsx

This makes the function generateToken() into a callback function so there is no endless loop in the useEffect.  It also adds keys to the children in the mapped elements.

fix error messages in quickstart

---

frontend/src/dataUtilities.ts

Fix for https://github.com/plaid/quickstart/issues/201

Fix for import line

---

.gitignore

add .vscode folder to and remove java from main level git ignore

add vscode to gitignore and remove java

---

python/server.py

Change Python environment variable from being hardcoded as "sandbox"

change Python environment variable

---

node/index.js

In the node file,
Fixed the pretty print function to print `response.data` rather than just `response`.
Also fixed error logging to be `error.response` rather than just `error`.

[LP - 442] Fix logs in node

---

.env.example
frontend/src/dataUtilities.ts
java/pom.xml
java/src/main/java/com/plaid/quickstart/resources/LinkTokenWithPaymentResource.java

Lw bump java

---

frontend/src/dataUtilities.ts

changed currency from US $ to iso currency codes

change currency to use iso currency codes

---

README.md

Change command to reflect whatever version of python someone is using

Fix readme to reflect any python version

---

go/Dockerfile
go/go.mod
go/go.sum
go/server.go

- updates the plaid-go version to 1.2.0
- updates the golang base image for the go Dockerfile

update plaid-go package

---

frontend/package-lock.json
frontend/package.json
frontend/src/Components/ProductTypes/Products.tsx
frontend/src/dataUtilities.ts
go/server.go
java/pom.xml
java/src/main/java/com/plaid/quickstart/QuickstartApplication.java
java/src/main/java/com/plaid/quickstart/resources/AccessTokenResource.java
java/src/main/java/com/plaid/quickstart/resources/TransferResource.java
node/index.js
node/package-lock.json
node/package.json
python/requirements.txt
python/server.py
ruby/Gemfile
ruby/Gemfile.lock
ruby/app.rb

* Backend client libraries updated to work with Transfer
* Node to `9.2.0`
* Ruby to `14.3.0`
* Python to `8.2.1`
* Java to `9.4.0`
* Front-end (working and complete)
* Updated Node client library to `9.2.0` to work with Transfer
* Added Transfer to `frontend/src/Components/ProductTypes/Products.tsx`
* Added Transfer to `frontend/src/dataUtilities.ts`
* Backend updates (`node/index.js`, `ruby/app.rb`):
* `TRANSFER_ID` variable to store transfer ID in memory
* If `transfer` is included product in `.env`, authorize and create transfer after successful token exchange
* `authorizeAndcreateTransfer()` helper function (excluding Java) called after successful token exchange

Add Transfer product

---

node/index.js

Payment amount reduced such that quickstart app does not show an error when configured for development environment, due to payment amount limits on development.

Change payment amount to 1.23 

---

python/server.py

To resolve `AttributeError: 'PlaidApi' object has no attribute 'investment_transactions_get'` error

Fix typo in /api/investments_transactions

---

python/requirements.txt

Changed `itsdangerous` version to resolve json failure.

Python backend with import json failure #323

---

node/index.js
node/package.json

Solve Node cross-origin error on browser

add cross-origin plugin

---

frontend/package-lock.json
go/go.mod
go/go.sum
go/server.go
node/index.js
node/package-lock.json
python/server.py

Update to latest Go version.
Add redirect URI to python.

update Go and run snyk

---

python/server.py

1) Fix python payment_initiation link creation
2) Add ability to have blank redirect URI in the .env file for python

add redirect logic

---

java/src/main/java/com/plaid/quickstart/resources/LinkTokenResource.java

JIRA [here](https://jira.plaid.com/browse/LP-633). We currently hard code the country codes in the java quickstart folder. This PR pulls the correct country codes form the .env file

[LP-633] fixing country codes issue for Java

---

python/Dockerfile

This reverts commit f5eeac6f656303ff18efacb82cb1a66288c95f1c.
Closes #373.

Revert "Update Dockerfile"

---

frontend/src/setupProxy.js

this fixes an extremely silly copy and paste error that caused https://github.com/plaid/quickstart/issues/405

fix quickstart 405

---

frontend/package.json
frontend/src/setupProxy.js

Fixes https://github.com/plaid/quickstart/issues/411

fix https://github.com/plaid/quickstart/issues/411

---

java/src/main/java/com/plaid/quickstart/QuickstartApplication.java
python/server.py
ruby/app.rb

Fixes typos introduced from PR #263

Fix typos in Transfer product comments

---

python/requirements.txt

I confirmed that without this line the build fails and that with it it works

fix https://github.com/plaid/quickstart/issues/442

---

README.md

Updating API settings link as it looks like this setting moved from `/team/api` to `/developers/api`.

Update API Settings Link in README.md

---

ruby/Gemfile
ruby/Gemfile.lock
ruby/app.rb

Adds CRA base report, income insights, and partner insight product support to ruby backend.

Adds CRA example ruby backend

---

java/pom.xml
java/src/main/java/com/plaid/quickstart/QuickstartApplication.java
java/src/main/java/com/plaid/quickstart/resources/CraResource.java
java/src/main/java/com/plaid/quickstart/resources/LinkTokenResource.java
java/src/main/java/com/plaid/quickstart/resources/UserTokenResource.java

Adds CRA base report, income insights, and partner insight product support to java backend.

Adds CRA example java backend

---

python/requirements.txt
python/server.py

Adds CRA base report, income insights, and partner insight product support to python backend.

Adds CRA example python backend

---

go/server.go
java/src/main/java/com/plaid/quickstart/resources/UserTokenResource.java
node/index.js
python/server.py
ruby/app.rb

With thanks to @RahulKhanna14 , I found out we weren't passing the user's birth date in any of our user token create requests; something that is now required. So I added it!

Added date of birth to user token
