- ruby/app.rb
Extremely minor fix, but one that cost me an `item` for the limited 5 dev items. 
As far as I know, you cannot find an item if you lose the access token and item id. This PR makes sure those are outputted so they are not lost.
> Fix puts display

- python/README.md
eba5b5e changed the Python quickstart to read tokens from the environment, but did not update the README to reflect this change.
> Update README.md to reflect values passed in env

- python/requirements.txt
- python/server.py
Updated to use Python 3 compatible print statements, and skipped installing wsgiref on Python 3 since it's now in the standard library. This now installs and runs fine for me on Python 3.
This should not break Python 2 compatibility.
> Python 3 compatibility

- node/README.md
- python/README.md
- ruby/README.md
- Remove `[` and `]` from API key placeholders
- Ensure quickstart app envvars are in a consistent order and always have single quotes
> make readme more consistent

- node/index.js
The `getAssetReport` in the Node client takes three non-optional arguments: the string token, a boolean indicating whether to include insights, and the callback. The second boolean argument is missing in the quickstart, which causes the callback to be `undefined` and results in an uncaught promise rejection.
> Add missing `includeInsights` argument to `getAssetReport` method in Node SDK

- ruby/views/index.erb
In the ruby quickstart example, the `Plaid.create` javascript function has key twice which breaks the app. Replacing the second `key` variable with `countryCodes` fixes the error.
> Update countryCode token in view

- go/README.md
The missing `\` causes the `go run server.go` command to run in a separate shell without the env vars set prior to it.
> Added the missing `\` in the run command

- python/static/style.css
Stylesheet linters will complain that the file has invalid CSS syntax unless this line is removed.
> Remove invalid property from python stylesheet

- node/README.md
- node/index.js
- node/views/index.ejs
- node/views/oauth-response.ejs
- The quickstart already supports the OAuth desktop flow even before this PR. 
- This PR adds support for the OAuth redirect flow (used for mobile web).
- This PR does not add support for the OAuth redirect + webview flow (used for mobile apps).
I tested that this PR works locally for the OAuth flows and does not break the existing classic Plaid Quickstart flow.
Note: The quickstart does not currently demonstrate the webview flow. Handling the webview flow requires defining URLs at the quickstart app to handle Link success and error (https://plaid.com/docs/#communication-between-link-and-your-app). This PR does not add webview support.
> Implements OAuth Node support

- go/README.md
- go/server.go
- java/README.md
- node/README.md
- node/index.js
- python/README.md
- python/server.py
- ruby/README.md
- ruby/views/index.erb
Clarify integrations by removing non-US country codes from most readmes and sample code.
> Remove country codes from most docs

- ruby/app.rb
- ruby/views/index.erb
* `client.payment_initiation.create_recipient` expects 4 instead of 3 parameters
* Fallback to `sandbox` env in erb if `ENV["PLAID_ENV"]` is unset.
> Fix ruby quickstart

- python/server.py
Here's my proposed fix for the server.py Python 3 ```TypeError```, as explained in Issue #53.
For Python 3, the ```bytes``` output of ```base64.b64encode(asset_report_pdf)``` should be decoded to ```str``` before passing the result to ```jsonify```.
My solution is redundant for Python 2.7 (decodes str to str), but because Python 2.7 is end-of-life in 2020, more developers will be using Python 3 over time. I considered using a ```try/except``` on the ```return jsonify({...```, but thought the extra code wasn't worth it, compared to incurring the slight inefficiency of Python 2 string-to-string decoding with this one-line fix. 
Tested with Python 2.7 and 3.7.
> Python 3 jsonify on PDF b64encode throws TypeError exception

- node/index.js
The Android sample app has been relying on the node quickstart sample as its server, so OAuth has been failing on the sample app since we aren't redirecting back to the app.
This also helps document for our customers that you need to add android_package_name if you want to enable OAuth in Android.
> ANDROID: Add android_package_name as parameter to link_token/create

- python/server.py
Fixes the issue described [here](https://github.com/plaid/quickstart/issues/50). Essentially, there is a bug where the `e` variable does not exist where it is called. Since the error we're throwing in this case is not a Plaid API error but rather a quickstart level error, we don't map any error_code or error_type to the error message.
> fix error object doesn't exist when called

- frontend/src/App.tsx
- frontend/src/Components/Headers/index.tsx
- frontend/src/Context/index.tsx
Jira ticket:  https://jira.plaid.com/browse/LP-412
This adds information on link token create errors to landing page.  The first message will still appear if the server is not running.  Otherwise if an error occurs in link_create_token, error messages will be displayed.
before: 
after:
> [LP 412] add link errors to landing page

- frontend/package-lock.json
- frontend/package.json
When trying to run the `quickstart` on an Apple computer using the new `Apple Silicon (M1 / arm64)`, the installation process fails due to `node-sass` not being compatible with the architecture (arm64), same for `fsevents`, this is not a direct dependency, `fsevents` is  being use by `webpack-dev-server`. 
`node-sass` hasn’t released a version compatible with the new  architecture (arm64) because of that the logical fix is to replace `node-sass` with `sass` which will give us the same result, but it's compatible with the `Apple silicon`.
In the other hand `fsevents` has a version compatible with the `Apple silicon`, so we only need to resolve to the desired version to have the app compatible with the `Apple silicon`.
> fix: Replace node-sass with sass and add fsevents resolution (Apple Silicon support)

- python/requirements.txt
- python/server.py
A change in the openAPI renamed amount to payment_amount in the python models and required a change in server.py.
In addition, the addition of a new datetime property to ACCOUNT model requires a fix to pretty_print_response function.
Also, remove printing of access_token and item_id in console.
> openAPI change name from amount to payment_amount

- python/server.py
server.py does not use the `PLAID_COUNTRY_CODES` environment variable for some reason. This was a source of great confusion when I tried to use python to start the backend. The fix is simple so I thought I would propose these changes.
> Fix country_codes in python/server.py

- README.md
Python 3.9.6 gives an ssl certification error.  Fix is to install root certificates.
> Add SSL certificate command to python instructions

- .env.example
Add comments to .env.example to state that development needs https:// and URI may be left blank
> clarify testing OAuth in development

- go/Dockerfile
- node/Dockerfile
- python/server.py
I ran into a few issues when attempting to run the different quickstart applications.
Issues:
* The Dockerfiles for Node and Go did not copy the `.env` files into the container. This broke environment variable loading via dotenv.
* The Python server was using `NumbersBACSNullable` instead of `RecipientBACSNullable`. This caused the `'/api/create_link_token_for_payment' to always fail.
> Fix Go, Node, and Python quickstart servers

- go/server.go
- java/src/main/java/com/plaid/quickstart/resources/AccessTokenResource.java
- node/index.js
- python/server.py
- ruby/app.rb
Without this fix the first atttempt at using the quickstart in the development environment seems doomed to fail if the payment initiation limit is set below GBP12.34. This PR reduces the amount to hopefully reduce the likelihood of needing to contact support to track down the error that occurs if the amount it too high.
> Updates the amount used in the payment initiation examples

- README.md
Use bash syntax blocks for bash commands (and guarantee to strip syntax highlighting from plain-text blocks)
~~~
```bash
echo "hello"
```
```txt
stdout: this is log output
```
~~~
Remove confusing use of `$` - because sysadmins who know what that means don't need to be told, and for people who don't, it's already the default behavior, so it's just confusing and makes it difficult to copy and paste.
> docs: add syntax highlighting, remove non-copiable characters

- .env.example
Turns out, our REDIRECT_URI requires a trailing slash if we're redirecting back to the root page. So I added one.
> Add a trailing slash to REDIRECT_URI example

- frontend/src/Components/ProductTypes/Products.tsx
Just a quick fix to hide the "Investments" entry from our list of endpoints to query if we didn't include it in our list of products when requesting a Link token.
> Hide Investments if it's not in product list

- frontend/src/dataUtilities.ts
Fix for typescript error below:
```
Type 'string | null' is not assignable to type 'string'.
Type 'null' is not assignable to type 'string'.  TS2322
468 |       name: account.name,
469 |       type: "credit card",
> 470 |       date: credit.last_payment_date,
|       
```^
> Default date to empty string to fix type error

- frontend/src/Components/Headers/index.tsx
https://jira.plaid.com/browse/DOCS-1008
Add better error messaging on link-create error.  
before:  
after:
> add messaging to link create error

- frontend/Dockerfile
- frontend/package-lock.json
- frontend/package.json
I did a little Googling and it looks like https://github.com/plaid/quickstart/issues/388 is caused by a bug in react-scripts 4.0.1 that is fixed in 4.0.2. See https://github.com/facebook/create-react-app/pull/9964. I was probably never able to reproduce this because I have npm 6 installed because I've never been able to get npm 7 to work properly with Artifactory, and this would most likely impact only npm 7+ users because earlier versions of npm don't care about peer deps.
If the reviewer happens to have npm 7 installed, and wants to test this...that would be cool.
This PR updates the version of react-scripts to 4.0.2.
Obligatory I-have-no-idea-what-I'm-doing-dog meme goes here.
> Fix npm installation failure issue (issue #388)

- frontend/Dockerfile
Attempting to launch the quickstart tutorial with docker-compose fails because the node version of the frontend's image is not allowed.
The node version of the base docker image (`node:lts-alpine`) is 18.12.0 (as of this writing). The frontend's `package.json` requires a node version of `<17.0.0`.
Because of this, the app fails to launch with `docker-compose`.
> **Note**: if you can run the app fine with `docker-compose`, it is most likely because you older version of `node:lts-alpine` which is running node 17 or earlier
You can follow the following steps to reproduce this issue:
```sh
docker pull node:lts-alpine 
make up language=python
```
When I run the above, the frontend image fails to build with this error :
```
> [quickstart-frontend 5/6] RUN npm install: …
```
> Pin node version in frontend/Dockefile

- .env.example
- README.md
The current wording of the quickstart makes it sound like you need to use a redirect URI to test OAuth, but you really don't, especially given the changes we've made in the past ~6 months to use pop-up flows whenever possible. Given how annoying it is to use a redirect URI with the quickstart, especially in production or development, the perceived need to setup redirect uris can be a barrier for entry to developers. This PR (spurred by a recent interaction with a developer on discord) clarifies that you probably don't need to use one.
> Make it clear you don't need a redirect URI

- python/server.py
Removed unused variable `asset_report_pdf`.
Removed unused imports:
```python
from flask import render_template
from plaid.exceptions import ApiException
from werkzeug.wrappers import response
```
Simplified import and usage of `datetime` functions.
Fixed a bug in `while num_retries_remaining > 0` code block, and the line just following it. In both the `error_response = ...` and `if asset_report_json ... ` blocks, the variable `e` was unbound. This is resolved by declaring `err` as None before the block, then assigning to `err` on each retry. `err` is then used after the `while` block. 
I also put an `else:` before the two lines starting with `error_response = ...` so they would actually run. My assumption is that these were meant to run if the error is anything aside from …
> Organize imports and fix "e" bug

- frontend/package.json
This fixes https://github.com/plaid/quickstart/issues/428 wherein the frontend will not start using node 18 (it works fine with node 16).
This fix is based on a suggestion I found here:
https://github.com/facebook/create-react-app/issues/12304
You'd think that removing this line would break things! But it didn't. I mean, at least not for me. 
Another approach I found that also fixed it was to export the environment variable `DANGEROUSLY_DISABLE_HOST_CHECK=true` as part of the start script, but the optics of that seemed a little bad.
> fix quickstart-428

- .env.example
When adding in environment variable PLAID_REDIRECT_URI=, I found that quote characters caused a misreference when adding the redirect URI in the Plaid dashboard. 1 PR = 1000 issues, so wanted to ship this update.
> Update .env.example use no quote characters for default redirect URI.

- go/go.mod
- go/go.sum
- go/server.go
version 18 of the go client library (released today) includes breaking changes that impact the quickstart; this brings the quickstart up to use the latest version.
> update go to v18

- java/src/main/java/com/plaid/quickstart/QuickstartApplication.java
- java/src/main/java/com/plaid/quickstart/resources/AssetsResource.java
- java/src/main/java/com/plaid/quickstart/resources/StatementsResource.java
For reasons unbeknownst to me, we never added asset reports to the java quickstart.
Once I figured out how to handle returning PDFs in Java (which I needed to do for the Statements quickstart) it was pretty easy to do this, so I did it. 
This also includes a little whitespace cleanup for the statements addition, which (while working on this) I realized was indented too far.
> Add assets to java

- go/server.go
- java/src/main/java/com/plaid/quickstart/resources/TransactionsResource.java
- node/index.js
- python/server.py
- ruby/app.rb
Prior to the Quickstart being migrated to `/transactions/sync` instead of `/transactions/get`, we used to have a retry loop so that if you requested transactions before they're ready, we would sleep for a few seconds and try again. After the migration to `/transactions/sync`, that code was lost, and now the current behavior is that if you click on the transactions sync button too quickly after Link completes, no transactions load when you click the button and it makes the Quickstart look broken. (This is most likely to happen if you are using Production rather than Sandbox, since Sandbox is artificially fast.) This PR fixes that behavior and restores the previous retry polling.
> Improve Quickstart behavior when pressing /transactions/sync very fast (fixes DOCS-1622)

- .env.example
The docs link in .env.example are dead and result in 404s. Update the links to the correct URLs.
> Update docs link in .env.example
